Contact add form
Manomenu/parafia-mkbm pull request #3
Opened 2023-07-15 13:46 UTC by Manomenu

Dodałem formularz do dodawania kontaktu (dynamiczny :) )

2023-07-15 18:54 UTC, boniffacy requested changes

2023-07-15 18:54 UTC, boniffacy commented on parafia-mbkm/ClientApp/src/app/contact/contact.component.ts
> +      .addContact(
error when adding contant withoyt any icon - needs handling this case. @Manomenu

2023-07-15 18:55 UTC, Manomenu commented on parafia-mbkm/ClientApp/src/app/contact/contact.component.ts
> +      .addContact(
nie działa??! :)

2023-07-15 18:59 UTC, boniffacy approved these changes

2023-07-15 22:20 UTC, Manomenu commented on parafia-mbkm/ClientApp/src/app/contact/contact.component.ts
> +      .addContact(
ok, @boniffacy  błąd był taki, że można było usunąć wybraną ikonę, co było zbędną funkcjonalnością lub można było pozostawić pole bez wyboru, wtedy dodawano nazwę w polu icon w tablicy w db, która nie była powiązana z jakąkolwiek ikonką w kodzie!

Proszę o ponowne sprawdzenie! :)

2023-07-15 22:24 UTC, Manomenu commented
Ogólnie to dodam jeszcze usuwanie tych kontaktów, ale to może w innym branchu

2023-07-16 14:25 UTC, boniffacy approved these changes

2023-07-16 14:25 UTC, boniffacy commented on parafia-mbkm/ClientApp/src/app/contact/contact.component.ts
> +      .addContact(
@Manomenu 
Błąd naprawiony, działa ładnie! :) 
humor gitówa -  mogę edytować ptaszka

2023-07-16 14:26 UTC, merged